# Generated by Django 2.1.7 on 2019-04-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0002_auto_20190426_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='librarylog',
            fields=[
                ('book_name', models.CharField(max_length=400)),
                ('book_id', models.IntegerField(default='42081710', primary_key=True, serialize=False)),
                ('author_first_name', models.CharField(max_length=100)),
                ('author_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_last_name', models.CharField(max_length=100)),
                ('year_of_publication', models.CharField(default='2019', max_length=4)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
        ),
    ]
