# Generated by Django 2.1.7 on 2019-04-26 05:51

from django.db import migrations
import gymlog.models


class Migration(migrations.Migration):

    dependencies = [
        ('gymlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlog',
            name='exitlog',
            field=gymlog.models.UnixTimestampField(auto_created=True, null=True),
        ),
    ]
