# Generated by Django 2.1.7 on 2019-04-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(default='Chandigarh', max_length=30)),
                ('state', models.CharField(default='Chandigarh', max_length=30)),
                ('branch', models.CharField(default='CS', max_length=10)),
                ('sid', models.IntegerField(default='17103036', max_length=8, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
    ]
