# Generated by Django 2.1.7 on 2019-04-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.IntegerField(default='17103036', primary_key=True, serialize=False),
        ),
    ]
